### PR TITLE
Adjusted list of template variables

### PR DESCRIPTION
**Pull request by dmitribatulin**
- Added additional variables for templates
- Added ability to add your own variables in settings.json
- Added ability to specify custom file to calculate variables

### CODE REVIEW

**Comment by dmitribatulin** [comment]
Please increment version. Thanks...

**Comment by dmitribatulin** [comment]
Could you please increment version... It is now 0.0.4, but must be 0.0.5 to retrieve updates in IDE

**Comment by visualzoran** [comment]
There was a small bug in your code, templates engine was crashing if custom variables javascript file was not defined in the setup. I've fixed it so it can work without that setting. New version of the extension is available in Visual Studio Marketplace now. Thank you for your modifications.

**Comment by dmitribatulin** [comment]
Many thanks for you changes. And a huge thanks for your extension. It is really helpful))

**Pull request merged**
